import Head from "next/head";
import { useState } from "react";
import { Alert, Button, Col, Container, Row } from "react-bootstrap";
import AddressInput from "@/components/AddressInput";
import CardNFT from "@/components/CardNFT";
import { getNFTAlchemy } from "./api/alchemy";

export default function Home() {
  const [nft, setNFT] = useState([]);
  const [error, setError] = useState(false);
  const [ownerAddress, setOwnerAddress] = useState("");
  const pageSize = 10;
  const [pageKey, setPageKey] = useState("");

  const getNFTByAddress = async (address, clearNFT = false) => {
    try {
      setError("");
      setOwnerAddress(address);
      const response = await getNFTAlchemy(address, pageKey, pageSize);
      if (response?.ownedNfts.length > 0) {
        setNFT(clearNFT ? response.ownedNfts : [...nft, ...response.ownedNfts]);
        setPageKey(response?.pageKey);
      } else {
        setError("No NFT where found for this address");
      }
    } catch (error) {
      setError(
        address
          ? "Something went wrong, please try again"
          : "Please remember to input an address"
      );
    }
  };

  const displayNFT = () => {
    return nft.map((item) => generateNFTToCard(item));
  };

  const generateNFTToCard = (nft) => {
    return (
      <CardNFT
        nft={nft}
        ownerAddress={ownerAddress}
        key={nft?.contract.address + nft?.tokenId}
      />
    );
  };

  const showErrorMessage = () => {
    return (
      <Row className="justify-content-center mt-5 bg">
        <Alert variant="danger">{error}</Alert>
      </Row>
    );
  };

  return (
    <>
      <Head>
        <title>Display NFTs by Address</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        fluid
        className="p-5 bg-dark text-white"
        style={{ minHeight: "100vh" }}
      >
        <Row className="text-center">
          <h2 className="mb-3">Welcome to the NFT displayer</h2>
          <p className="mb-5">Please type an address to see their NFT</p>
        </Row>
        <Row className="justify-content-center">
          <Col sm={6} xs={12}>
            <AddressInput onClick={getNFTByAddress} />
          </Col>
        </Row>
        <Row>
          {error && showErrorMessage()}
          {nft.length > 0 && (
            <>
              <Row>
                <h2 className="mt-5 mb-5">NFT for this address</h2>
              </Row>
              <Row className="justify-content-center">{displayNFT()}</Row>
              <Row className="justify-content-center">
                <Button
                  className="mx-auto w-50"
                  onClick={() => getNFTByAddress(ownerAddress)}
                  disabled={!pageKey}
                >
                  Load More
                </Button>
              </Row>
            </>
          )}
        </Row>
      </Container>
    </>
  );
}
